/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PdfPageNumbersPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: true,
  position: "bottom-center",
  format: "page-of-total",
  customFormat: "Page {{page}} of {{total}}",
  fontSize: 10,
  fontFamily: "sans-serif",
  marginBottom: 20,
  marginTop: 20,
  marginSide: 20,
  skipFirstPage: false,
  color: "#666666"
};
var PdfPageNumbersSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Page numbers").setHeading();
    this.displayExportToggle(containerEl);
    new import_obsidian.Setting(containerEl).setName("Position").setDesc("Where to place page numbers on the page").addDropdown(
      (dropdown) => dropdown.addOption("bottom-center", "Bottom center").addOption("bottom-left", "Bottom left").addOption("bottom-right", "Bottom right").addOption("top-center", "Top center").addOption("top-left", "Top left").addOption("top-right", "Top right").setValue(this.plugin.settings.position).onChange(async (value) => {
        this.plugin.settings.position = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Format").setDesc("How to display the page number").addDropdown(
      (dropdown) => dropdown.addOption("page-only", "1").addOption("page-of-total", "Page 1 of 5").addOption("custom", "Custom format").setValue(this.plugin.settings.format).onChange(async (value) => {
        this.plugin.settings.format = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.format === "custom") {
      new import_obsidian.Setting(containerEl).setName("Custom format").setDesc(
        "Use {{page}} for current page and {{total}} for total pages"
      ).addText(
        (text) => text.setPlaceholder("Page {{page}} of {{total}}").setValue(this.plugin.settings.customFormat).onChange(async (value) => {
          this.plugin.settings.customFormat = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Font size").setDesc("Font size in points").addSlider(
      (slider) => slider.setLimits(6, 24, 1).setValue(this.plugin.settings.fontSize).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.fontSize = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Font family").setDesc("Font family for page numbers").addText(
      (text) => text.setPlaceholder("Sans-serif").setValue(this.plugin.settings.fontFamily).onChange(async (value) => {
        this.plugin.settings.fontFamily = value || "sans-serif";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Color").setDesc("Page number text color (hex)").addText(
      (text) => text.setPlaceholder("#666666").setValue(this.plugin.settings.color).onChange(async (value) => {
        this.plugin.settings.color = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Skip first page").setDesc("Don't show a page number on the first page").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.skipFirstPage).onChange(async (value) => {
        this.plugin.settings.skipFirstPage = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Bottom margin").setDesc("Distance from the bottom edge of the page").addSlider(
      (slider) => slider.setLimits(0, 80, 1).setValue(this.plugin.settings.marginBottom).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.marginBottom = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Top margin").setDesc("Distance from the top edge of the page").addSlider(
      (slider) => slider.setLimits(0, 80, 1).setValue(this.plugin.settings.marginTop).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.marginTop = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Side margin").setDesc(
      "Horizontal padding in pixels (for left/right positions)"
    ).addSlider(
      (slider) => slider.setLimits(0, 60, 1).setValue(this.plugin.settings.marginSide).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.marginSide = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("p", {
      text: "When exporting to PDF, set enough page margins in the export dialog so the page numbers have room to display.",
      cls: "setting-item-description"
    });
  }
  displayExportToggle(containerEl) {
    new import_obsidian.Setting(containerEl).setName("Enable page numbers").setDesc("Add page numbers when exporting to PDF.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var ORIGINAL_PRINT_TO_PDF = Symbol("pdf-page-numbers-original");
var WEBVIEW_READY_HANDLER = Symbol("pdf-page-numbers-webview-ready");
var PdfPageNumbersPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.patchedTargets = /* @__PURE__ */ new Set();
    this.activePrintRoots = /* @__PURE__ */ new Map();
    this.popupMonitors = /* @__PURE__ */ new Map();
    this.originalWindowOpen = null;
    this.originalWindowPrint = null;
    this.printObserver = null;
    this.webviewObserver = null;
    this.exportDialogObserver = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new PdfPageNumbersSettingTab(this.app, this));
    this.patchWindowOpen();
    this.patchWindowPrint();
    this.observePrintRoots();
    this.patchPrintSurfaces();
    this.observeWebviews();
    this.observeExportDialogs();
  }
  onunload() {
    this.clearActivePrintRoots();
    this.restoreWindowOpen();
    this.restoreWindowPrint();
    this.restorePrintToPDF();
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshActivePrintRoots();
  }
  // ── Template builder ───────────────────────────────────────────
  /**
   * Build the HTML template for Electron's header/footer.
   *
   * Electron replaces special CSS class names with actual values:
   *   <span class="pageNumber"></span>  → current page number
   *   <span class="totalPages"></span>  → total page count
   *
   * IMPORTANT: The default template font-size is 0, so we must
   * explicitly set font-size on all elements.
   */
  buildTemplate() {
    const s = this.settings;
    let textAlign = "center";
    let padding = "0";
    if (s.position.endsWith("left")) {
      textAlign = "left";
      padding = `0 0 0 ${s.marginSide}px`;
    } else if (s.position.endsWith("right")) {
      textAlign = "right";
      padding = `0 ${s.marginSide}px 0 0`;
    }
    let content;
    switch (s.format) {
      case "page-only":
        content = '<span class="pageNumber"></span>';
        break;
      case "page-of-total":
        content = 'Page <span class="pageNumber"></span> of <span class="totalPages"></span>';
        break;
      case "custom":
        content = s.customFormat.replace(
          /\{\{page\}\}/g,
          '<span class="pageNumber"></span>'
        ).replace(
          /\{\{total\}\}/g,
          '<span class="totalPages"></span>'
        );
        break;
      default:
        content = '<span class="pageNumber"></span>';
    }
    const fontFamily = s.fontFamily === "inherit" ? "sans-serif" : s.fontFamily;
    return `<div style="width: 100%; font-size: ${s.fontSize}px; font-family: ${fontFamily}; color: ${s.color}; text-align: ${textAlign}; padding: ${padding}; -webkit-print-color-adjust: exact; print-color-adjust: exact;">${content}</div>`;
  }
  patchWindowPrint() {
    if (this.originalWindowPrint)
      return;
    this.originalWindowPrint = window.print.bind(window);
    const beforePrintHandler = () => {
      this.preparePrintRoots();
    };
    const afterPrintHandler = () => {
      window.setTimeout(() => this.cleanupDetachedPrintRoots(), 250);
    };
    window.addEventListener("beforeprint", beforePrintHandler);
    window.addEventListener("afterprint", afterPrintHandler);
    window.print = () => {
      var _a;
      this.preparePrintRoots();
      (_a = this.originalWindowPrint) == null ? void 0 : _a.call(this);
    };
    this.register(() => {
      window.removeEventListener("beforeprint", beforePrintHandler);
      window.removeEventListener("afterprint", afterPrintHandler);
    });
  }
  patchWindowOpen() {
    if (this.originalWindowOpen)
      return;
    this.originalWindowOpen = window.open.bind(window);
    window.open = (...args) => {
      const popup = this.originalWindowOpen(...args);
      if (popup) {
        this.monitorPopupWindow(popup);
      }
      return popup;
    };
  }
  restoreWindowOpen() {
    if (!this.originalWindowOpen)
      return;
    window.open = this.originalWindowOpen;
    this.originalWindowOpen = null;
    for (const intervalId of Array.from(this.popupMonitors.values())) {
      window.clearInterval(intervalId);
    }
    this.popupMonitors.clear();
  }
  monitorPopupWindow(popup) {
    if (this.popupMonitors.has(popup))
      return;
    const intervalId = window.setInterval(() => {
      if (popup.closed) {
        window.clearInterval(intervalId);
        this.popupMonitors.delete(popup);
        return;
      }
      try {
        this.patchPopupPrintIpc(popup);
      } catch (e) {
      }
    }, 100);
    this.popupMonitors.set(popup, intervalId);
  }
  patchPopupPrintIpc(popup) {
    var _a;
    const ipcRenderer = (_a = popup.electron) == null ? void 0 : _a.ipcRenderer;
    if (!ipcRenderer || typeof ipcRenderer.send !== "function")
      return;
    const sendTarget = ipcRenderer;
    if (sendTarget[ORIGINAL_PRINT_TO_PDF])
      return;
    sendTarget[ORIGINAL_PRINT_TO_PDF] = sendTarget.send.bind(sendTarget);
    sendTarget.send = (channel, ...args) => {
      if (channel === "print-to-pdf" && args.length > 0) {
        args[0] = this.applyPageNumberOptions(args[0]);
      }
      return sendTarget[ORIGINAL_PRINT_TO_PDF](channel, ...args);
    };
    this.patchedTargets.add(sendTarget);
    const intervalId = this.popupMonitors.get(popup);
    if (intervalId !== void 0) {
      window.clearInterval(intervalId);
      this.popupMonitors.delete(popup);
    }
  }
  restoreWindowPrint() {
    if (!this.originalWindowPrint)
      return;
    window.print = this.originalWindowPrint;
    this.originalWindowPrint = null;
  }
  observePrintRoots() {
    const body = document.body;
    if (!body)
      return;
    this.preparePrintRoots(body);
    this.printObserver = new MutationObserver((mutations) => {
      for (const mutation of Array.from(mutations)) {
        if (mutation.target instanceof HTMLElement) {
          const activePrintRoot = mutation.target.closest(".print");
          if (activePrintRoot instanceof HTMLElement) {
            this.attachPageNumbers(activePrintRoot);
          }
        }
        for (const node of Array.from(mutation.addedNodes)) {
          if (node instanceof HTMLElement) {
            this.preparePrintRoots(node);
          }
        }
        for (const node of Array.from(mutation.removedNodes)) {
          if (node instanceof HTMLElement) {
            this.cleanupDetachedPrintRoots(node);
          }
        }
      }
    });
    this.printObserver.observe(body, {
      childList: true,
      subtree: true
    });
    this.register(() => {
      var _a;
      (_a = this.printObserver) == null ? void 0 : _a.disconnect();
      this.printObserver = null;
    });
  }
  preparePrintRoots(root = document.body) {
    for (const printRoot of this.findPrintRoots(root)) {
      this.attachPageNumbers(printRoot);
    }
  }
  findPrintRoots(root) {
    var _a, _b;
    const roots = /* @__PURE__ */ new Set();
    if (root instanceof HTMLElement && this.isPrintRoot(root)) {
      roots.add(root);
    }
    const printNodes = (_b = (_a = root.querySelectorAll) == null ? void 0 : _a.call(root, ".print")) != null ? _b : [];
    for (const node of Array.from(printNodes)) {
      if (node instanceof HTMLElement) {
        roots.add(node);
      }
    }
    return roots;
  }
  isPrintRoot(el) {
    return el.classList.contains("print") || el.classList.contains("print-preview");
  }
  attachPageNumbers(printRoot) {
    const existingCleanup = this.activePrintRoots.get(printRoot);
    if (existingCleanup) {
      existingCleanup();
      this.activePrintRoots.delete(printRoot);
    }
    if (!this.settings.enabled)
      return;
    const cleanup = this.injectPageNumbers(printRoot);
    this.activePrintRoots.set(printRoot, cleanup);
  }
  refreshActivePrintRoots() {
    for (const printRoot of Array.from(this.activePrintRoots.keys())) {
      const cleanup = this.activePrintRoots.get(printRoot);
      cleanup == null ? void 0 : cleanup();
      this.activePrintRoots.delete(printRoot);
      if (printRoot.isConnected) {
        this.attachPageNumbers(printRoot);
      }
    }
  }
  cleanupDetachedPrintRoots(root) {
    for (const [printRoot, cleanup] of Array.from(
      this.activePrintRoots.entries()
    )) {
      if (!printRoot.isConnected || root && root.contains(printRoot)) {
        cleanup();
        this.activePrintRoots.delete(printRoot);
      }
    }
  }
  clearActivePrintRoots() {
    for (const cleanup of Array.from(this.activePrintRoots.values())) {
      cleanup();
    }
    this.activePrintRoots.clear();
  }
  injectPageNumbers(printRoot) {
    var _a;
    const doc = printRoot.ownerDocument;
    const injected = [];
    const cleanupTasks = [];
    const previewRoot = (_a = printRoot.querySelector(".markdown-preview-view")) != null ? _a : printRoot;
    const pageContainers = this.findPageContainers(previewRoot);
    const pageBreaks = this.findPageBreaks(previewRoot);
    if (pageContainers.length > 1) {
      const total = pageContainers.length;
      pageContainers.forEach((container, index) => {
        const cleanup = this.preparePageContainer(container);
        if (cleanup)
          cleanupTasks.push(cleanup);
        const pageNumberEl = this.createPageNumberEl(
          doc,
          index + 1,
          total,
          true
        );
        container.appendChild(pageNumberEl);
        injected.push(pageNumberEl);
      });
    } else if (pageBreaks.length > 0) {
      const total = pageBreaks.length + 1;
      pageBreaks.forEach((pageBreak, index) => {
        var _a2;
        const pageNumberEl = this.createPageNumberEl(
          doc,
          index + 1,
          total,
          false
        );
        (_a2 = pageBreak.parentElement) == null ? void 0 : _a2.insertBefore(pageNumberEl, pageBreak);
        injected.push(pageNumberEl);
      });
      const lastBreak = pageBreaks[pageBreaks.length - 1];
      if (lastBreak == null ? void 0 : lastBreak.parentElement) {
        const pageNumberEl = this.createPageNumberEl(
          doc,
          total,
          total,
          false
        );
        lastBreak.parentElement.appendChild(pageNumberEl);
        injected.push(pageNumberEl);
      }
    } else {
      const pageNumberEl = this.createPageNumberEl(doc, 1, 1, false);
      previewRoot.appendChild(pageNumberEl);
      injected.push(pageNumberEl);
    }
    return () => {
      for (const injectedNode of injected) {
        injectedNode.remove();
      }
      for (const cleanup of cleanupTasks) {
        cleanup();
      }
    };
  }
  findPageContainers(previewRoot) {
    const directChildren = Array.from(previewRoot.children).filter(
      (child) => child instanceof HTMLElement
    );
    const visibleChildren = directChildren.filter(
      (child) => this.isVisibleElement(child)
    );
    const pageLikeChildren = visibleChildren.filter(
      (child) => this.looksLikePageContainer(child)
    );
    if (pageLikeChildren.length > 1) {
      return pageLikeChildren;
    }
    const explicitPages = Array.from(
      previewRoot.querySelectorAll(
        ".print-page, .page[data-page-number], [data-pdf-page]"
      )
    ).filter((child) => this.isVisibleElement(child));
    return explicitPages;
  }
  findPageBreaks(previewRoot) {
    return Array.from(
      previewRoot.querySelectorAll(
        ".pdf-page-break, hr.page-break, [style*='page-break'], [style*='break-before'], [style*='break-after']"
      )
    ).filter((pageBreak) => this.isVisibleElement(pageBreak));
  }
  looksLikePageContainer(el) {
    const computed = window.getComputedStyle(el);
    return el.classList.contains("page") || el.classList.contains("print-page") || computed.breakAfter !== "auto" || computed.breakBefore !== "auto" || computed.pageBreakAfter !== "auto" || computed.pageBreakBefore !== "auto";
  }
  isVisibleElement(el) {
    const computed = window.getComputedStyle(el);
    return computed.display !== "none" && computed.visibility !== "hidden" && el.offsetHeight > 0;
  }
  preparePageContainer(container) {
    if (window.getComputedStyle(container).position !== "static") {
      return null;
    }
    container.classList.add("pdf-page-numbers-page-container");
    return () => {
      container.classList.remove("pdf-page-numbers-page-container");
    };
  }
  createPageNumberEl(doc, page, total, overlay) {
    const pageNumberEl = doc.createElement("div");
    pageNumberEl.className = "pdf-page-number";
    pageNumberEl.textContent = this.formatPageNumber(page, total);
    if (page === 1 && this.settings.skipFirstPage) {
      pageNumberEl.classList.add("skip");
    }
    this.applyPageNumberStyle(pageNumberEl, overlay);
    return pageNumberEl;
  }
  formatPageNumber(page, total) {
    switch (this.settings.format) {
      case "page-only":
        return `${page}`;
      case "page-of-total":
        return `Page ${page} of ${total}`;
      case "custom":
        return this.settings.customFormat.replace(/\{\{page\}\}/g, `${page}`).replace(/\{\{total\}\}/g, `${total}`);
      default:
        return `${page}`;
    }
  }
  applyPageNumberStyle(pageNumberEl, overlay) {
    const isTop = this.settings.position.startsWith("top");
    const style = pageNumberEl.style;
    style.fontSize = `${this.settings.fontSize}pt`;
    style.fontFamily = this.settings.fontFamily;
    style.color = this.settings.color;
    style.width = "100%";
    style.left = "0";
    style.right = "0";
    style.textAlign = this.settings.position.endsWith("left") ? "left" : this.settings.position.endsWith("right") ? "right" : "center";
    style.paddingLeft = this.settings.position.endsWith("left") ? `${this.settings.marginSide}px` : "0";
    style.paddingRight = this.settings.position.endsWith("right") ? `${this.settings.marginSide}px` : "0";
    style.boxSizing = "border-box";
    style.zIndex = "999";
    if (overlay) {
      style.position = "absolute";
      style.top = isTop ? `${this.settings.marginTop}px` : "";
      style.bottom = isTop ? "" : `${this.settings.marginBottom}px`;
    } else {
      style.position = "relative";
      style.marginTop = isTop ? `${this.settings.marginTop}px` : "12px";
      style.marginBottom = isTop ? "12px" : `${this.settings.marginBottom}px`;
    }
  }
  patchPrintSurfaces() {
    var _a, _b;
    this.patchElectronPrintTargets();
    this.patchWebviewsIn(document.body);
    const remote = getElectronRemote();
    const onBrowserWindowCreated = (_event, window2) => {
      this.patchPrintTarget(window2 == null ? void 0 : window2.webContents);
    };
    (_b = (_a = remote == null ? void 0 : remote.app) == null ? void 0 : _a.on) == null ? void 0 : _b.call(_a, "browser-window-created", onBrowserWindowCreated);
    this.register(() => {
      var _a2, _b2;
      (_b2 = (_a2 = remote == null ? void 0 : remote.app) == null ? void 0 : _a2.removeListener) == null ? void 0 : _b2.call(
        _a2,
        "browser-window-created",
        onBrowserWindowCreated
      );
    });
    this.registerInterval(
      window.setInterval(() => {
        this.patchElectronPrintTargets();
        this.patchWebviewsIn(document.body);
      }, 2e3)
    );
  }
  patchElectronPrintTargets() {
    var _a, _b, _c, _d, _e, _f, _g;
    try {
      const remote = getElectronRemote();
      if (!remote)
        return;
      this.patchPrintTarget((_a = remote.getCurrentWebContents) == null ? void 0 : _a.call(remote));
      const windows = (_d = (_c = (_b = remote.BrowserWindow) == null ? void 0 : _b.getAllWindows) == null ? void 0 : _c.call(_b)) != null ? _d : [];
      for (const window2 of windows) {
        this.patchPrintTarget(window2 == null ? void 0 : window2.webContents);
      }
      const webContentsTargets = (_g = (_f = (_e = remote.webContents) == null ? void 0 : _e.getAllWebContents) == null ? void 0 : _f.call(_e)) != null ? _g : [];
      for (const webContents of webContentsTargets) {
        this.patchPrintTarget(webContents);
      }
    } catch (e) {
      console.error(
        "PDF Page Numbers: failed while scanning print targets",
        e
      );
    }
  }
  patchPrintTarget(target) {
    if (!target || typeof target.printToPDF !== "function")
      return;
    if (target[ORIGINAL_PRINT_TO_PDF])
      return;
    target[ORIGINAL_PRINT_TO_PDF] = target.printToPDF.bind(target);
    target.printToPDF = async (options = {}) => {
      return target[ORIGINAL_PRINT_TO_PDF](
        this.applyPageNumberOptions(options)
      );
    };
    this.patchedTargets.add(target);
  }
  applyPageNumberOptions(options = {}) {
    var _a, _b;
    if (!this.settings.enabled)
      return options;
    const isTop = this.settings.position.startsWith("top");
    const template = this.buildTemplate();
    const emptyTemplate = "<span></span>";
    return {
      ...options,
      displayHeaderFooter: true,
      headerTemplate: isTop ? template : (_a = options.headerTemplate) != null ? _a : emptyTemplate,
      footerTemplate: isTop ? (_b = options.footerTemplate) != null ? _b : emptyTemplate : template,
      margins: this.ensureMarginSpace(
        options.margins,
        isTop ? "top" : "bottom"
      )
    };
  }
  ensureMarginSpace(margins, requiredEdge) {
    var _a;
    if (!margins)
      return margins;
    const marginType = margins.marginType;
    const hasNoMargins = marginType === "none" || marginType === 0 || marginType === "0";
    const isCustomMargin = marginType === "custom" || marginType === 2 || marginType === 3 || marginType === "2" || marginType === "3";
    if (hasNoMargins) {
      return {
        marginType: "custom",
        top: requiredEdge === "top" ? 0.3 : 0.1,
        bottom: requiredEdge === "bottom" ? 0.3 : 0.1,
        left: 0.1,
        right: 0.1
      };
    }
    if (!isCustomMargin)
      return margins;
    const nextMargins = { ...margins };
    nextMargins[requiredEdge] = Math.max(
      Number((_a = nextMargins[requiredEdge]) != null ? _a : 0),
      0.3
    );
    return nextMargins;
  }
  patchWebviewsIn(root) {
    var _a, _b;
    if (!root)
      return;
    if (root instanceof HTMLElement && root.tagName === "WEBVIEW") {
      this.patchWebview(root);
    }
    const webviews = (_b = (_a = root.querySelectorAll) == null ? void 0 : _a.call(root, "webview")) != null ? _b : [];
    for (const webview of Array.from(webviews)) {
      this.patchWebview(webview);
    }
  }
  patchWebview(webview) {
    var _a;
    if (!webview)
      return;
    if (typeof webview.printToPDF === "function") {
      this.patchPrintTarget(webview);
      return;
    }
    if (webview[WEBVIEW_READY_HANDLER])
      return;
    const handleReady = () => {
      var _a2;
      if (typeof webview.printToPDF !== "function")
        return;
      this.patchPrintTarget(webview);
      (_a2 = webview.removeEventListener) == null ? void 0 : _a2.call(webview, "dom-ready", handleReady);
      delete webview[WEBVIEW_READY_HANDLER];
    };
    webview[WEBVIEW_READY_HANDLER] = handleReady;
    (_a = webview.addEventListener) == null ? void 0 : _a.call(webview, "dom-ready", handleReady, {
      once: true
    });
    window.setTimeout(handleReady, 0);
  }
  observeWebviews() {
    const body = document.body;
    if (!body)
      return;
    this.webviewObserver = new MutationObserver((mutations) => {
      for (const mutation of Array.from(mutations)) {
        for (const node of Array.from(mutation.addedNodes)) {
          if (node instanceof HTMLElement) {
            this.patchWebviewsIn(node);
          }
        }
      }
    });
    this.webviewObserver.observe(body, {
      childList: true,
      subtree: true
    });
    this.register(() => {
      var _a;
      (_a = this.webviewObserver) == null ? void 0 : _a.disconnect();
      this.webviewObserver = null;
    });
  }
  observeExportDialogs() {
    const body = document.body;
    if (!body)
      return;
    this.injectExportDialogToggle(body);
    this.exportDialogObserver = new MutationObserver((mutations) => {
      for (const mutation of Array.from(mutations)) {
        for (const node of Array.from(mutation.addedNodes)) {
          if (node instanceof HTMLElement) {
            this.injectExportDialogToggle(node);
          }
        }
      }
    });
    this.exportDialogObserver.observe(body, {
      childList: true,
      subtree: true
    });
    this.register(() => {
      var _a;
      (_a = this.exportDialogObserver) == null ? void 0 : _a.disconnect();
      this.exportDialogObserver = null;
    });
  }
  injectExportDialogToggle(root) {
    var _a, _b, _c, _d;
    const modals = /* @__PURE__ */ new Set();
    if (root instanceof HTMLElement && root.matches(".modal, .modal-container")) {
      modals.add(root);
    }
    const modalNodes = (_b = (_a = root.querySelectorAll) == null ? void 0 : _a.call(root, ".modal, .modal-container")) != null ? _b : [];
    for (const modal of Array.from(modalNodes)) {
      if (modal instanceof HTMLElement) {
        modals.add(modal);
      }
    }
    for (const modal of modals) {
      if (!this.isPdfExportDialog(modal))
        continue;
      if (modal.querySelector(".pdf-page-numbers-export-setting"))
        continue;
      const contentEl = (_d = (_c = modal.querySelector(".modal-content")) != null ? _c : modal.querySelector(".modal")) != null ? _d : modal;
      const settingHost = document.createElement("div");
      settingHost.className = "pdf-page-numbers-export-setting";
      const footerEl = contentEl.querySelector(
        ".modal-button-container, .modal-footer"
      );
      contentEl.insertBefore(settingHost, footerEl != null ? footerEl : null);
      new PdfPageNumbersSettingTab(this.app, this).displayExportToggle(
        settingHost
      );
    }
  }
  isPdfExportDialog(modal) {
    var _a, _b, _c, _d, _e;
    const title = (_c = (_b = (_a = modal.querySelector(".modal-title")) == null ? void 0 : _a.textContent) == null ? void 0 : _b.toLowerCase()) != null ? _c : "";
    const text = (_e = (_d = modal.textContent) == null ? void 0 : _d.toLowerCase()) != null ? _e : "";
    if (title.includes("export to pdf"))
      return true;
    const exportButton = Array.from(modal.querySelectorAll("button")).some(
      (button) => {
        var _a2;
        return /export|save/i.test((_a2 = button.textContent) != null ? _a2 : "");
      }
    );
    const markers = ["page size", "margins", "landscape", "scale", "pdf"].filter((marker) => text.includes(marker)).length;
    return text.includes("pdf") && exportButton && markers >= 2;
  }
  restorePrintToPDF() {
    var _a;
    for (const target of this.patchedTargets) {
      if (target[ORIGINAL_PRINT_TO_PDF]) {
        if (typeof target.printToPDF === "function") {
          target.printToPDF = target[ORIGINAL_PRINT_TO_PDF];
        } else if ("send" in target) {
          target.send = target[ORIGINAL_PRINT_TO_PDF];
        }
        delete target[ORIGINAL_PRINT_TO_PDF];
      }
      if (target[WEBVIEW_READY_HANDLER]) {
        (_a = target.removeEventListener) == null ? void 0 : _a.call(
          target,
          "dom-ready",
          target[WEBVIEW_READY_HANDLER]
        );
        delete target[WEBVIEW_READY_HANDLER];
      }
    }
    this.patchedTargets.clear();
  }
};
function getElectronRemote() {
  try {
    const electron = require("electron");
    if (electron.remote)
      return electron.remote;
  } catch (e) {
  }
  try {
    return require("@electron/remote");
  } catch (e) {
  }
  return null;
}

/* nosourcemap */